run:
  # default concurrency is a available CPU number
  concurrency: 4
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 2m
  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1
  # include test files or not, default is true
  tests: false
  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

  skip-files:
    - ".*/mock/.*.go"
    - ".*testing.go"

linters:
  disable-all: true
  enable:
    - deadcode
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - gocritic
    - gocyclo
    - gofmt
    - lll
    # - errcheck
    # - funlen
    # - cyclop
    # - errorlint
    # - gochecknoglobals
    # - gochecknoinits
    # - goconst
    # - godox
    # - goerr113
    # - gomnd
    # - ifshort
    # - wsl
  fast: false
