// Code generated by MockGen. DO NOT EDIT.
// Source: engine_abac_policy.go

// Package mock is a generated GoMock package.
package mock

import (
	dao "iam/pkg/database/dao"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEngineAbacPolicyManager is a mock of EngineAbacPolicyManager interface.
type MockEngineAbacPolicyManager struct {
	ctrl     *gomock.Controller
	recorder *MockEngineAbacPolicyManagerMockRecorder
}

// MockEngineAbacPolicyManagerMockRecorder is the mock recorder for MockEngineAbacPolicyManager.
type MockEngineAbacPolicyManagerMockRecorder struct {
	mock *MockEngineAbacPolicyManager
}

// NewMockEngineAbacPolicyManager creates a new mock instance.
func NewMockEngineAbacPolicyManager(ctrl *gomock.Controller) *MockEngineAbacPolicyManager {
	mock := &MockEngineAbacPolicyManager{ctrl: ctrl}
	mock.recorder = &MockEngineAbacPolicyManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngineAbacPolicyManager) EXPECT() *MockEngineAbacPolicyManagerMockRecorder {
	return m.recorder
}

// GetMaxPKBeforeUpdatedAt mocks base method.
func (m *MockEngineAbacPolicyManager) GetMaxPKBeforeUpdatedAt(updatedAt int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxPKBeforeUpdatedAt", updatedAt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaxPKBeforeUpdatedAt indicates an expected call of GetMaxPKBeforeUpdatedAt.
func (mr *MockEngineAbacPolicyManagerMockRecorder) GetMaxPKBeforeUpdatedAt(updatedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxPKBeforeUpdatedAt", reflect.TypeOf((*MockEngineAbacPolicyManager)(nil).GetMaxPKBeforeUpdatedAt), updatedAt)
}

// ListBetweenPK mocks base method.
func (m *MockEngineAbacPolicyManager) ListBetweenPK(expiredAt, minPK, maxPK int64) ([]dao.EngineAbacPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBetweenPK", expiredAt, minPK, maxPK)
	ret0, _ := ret[0].([]dao.EngineAbacPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBetweenPK indicates an expected call of ListBetweenPK.
func (mr *MockEngineAbacPolicyManagerMockRecorder) ListBetweenPK(expiredAt, minPK, maxPK interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBetweenPK", reflect.TypeOf((*MockEngineAbacPolicyManager)(nil).ListBetweenPK), expiredAt, minPK, maxPK)
}

// ListByPKs mocks base method.
func (m *MockEngineAbacPolicyManager) ListByPKs(pks []int64) ([]dao.EngineAbacPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPKs", pks)
	ret0, _ := ret[0].([]dao.EngineAbacPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPKs indicates an expected call of ListByPKs.
func (mr *MockEngineAbacPolicyManagerMockRecorder) ListByPKs(pks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPKs", reflect.TypeOf((*MockEngineAbacPolicyManager)(nil).ListByPKs), pks)
}

// ListPKBetweenUpdatedAt mocks base method.
func (m *MockEngineAbacPolicyManager) ListPKBetweenUpdatedAt(beginUpdatedAt, endUpdatedAt int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPKBetweenUpdatedAt", beginUpdatedAt, endUpdatedAt)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPKBetweenUpdatedAt indicates an expected call of ListPKBetweenUpdatedAt.
func (mr *MockEngineAbacPolicyManagerMockRecorder) ListPKBetweenUpdatedAt(beginUpdatedAt, endUpdatedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPKBetweenUpdatedAt", reflect.TypeOf((*MockEngineAbacPolicyManager)(nil).ListPKBetweenUpdatedAt), beginUpdatedAt, endUpdatedAt)
}
