// Code generated by MockGen. DO NOT EDIT.
// Source: engine_rbac_policy.go

// Package mock is a generated GoMock package.
package mock

import (
	dao "iam/pkg/database/dao"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEngineRbacPolicyManager is a mock of EngineRbacPolicyManager interface.
type MockEngineRbacPolicyManager struct {
	ctrl     *gomock.Controller
	recorder *MockEngineRbacPolicyManagerMockRecorder
}

// MockEngineRbacPolicyManagerMockRecorder is the mock recorder for MockEngineRbacPolicyManager.
type MockEngineRbacPolicyManagerMockRecorder struct {
	mock *MockEngineRbacPolicyManager
}

// NewMockEngineRbacPolicyManager creates a new mock instance.
func NewMockEngineRbacPolicyManager(ctrl *gomock.Controller) *MockEngineRbacPolicyManager {
	mock := &MockEngineRbacPolicyManager{ctrl: ctrl}
	mock.recorder = &MockEngineRbacPolicyManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngineRbacPolicyManager) EXPECT() *MockEngineRbacPolicyManagerMockRecorder {
	return m.recorder
}

// GetMaxPKBeforeUpdatedAt mocks base method.
func (m *MockEngineRbacPolicyManager) GetMaxPKBeforeUpdatedAt(updatedAt int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxPKBeforeUpdatedAt", updatedAt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaxPKBeforeUpdatedAt indicates an expected call of GetMaxPKBeforeUpdatedAt.
func (mr *MockEngineRbacPolicyManagerMockRecorder) GetMaxPKBeforeUpdatedAt(updatedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxPKBeforeUpdatedAt", reflect.TypeOf((*MockEngineRbacPolicyManager)(nil).GetMaxPKBeforeUpdatedAt), updatedAt)
}

// ListBetweenPK mocks base method.
func (m *MockEngineRbacPolicyManager) ListBetweenPK(minPK, maxPK int64) ([]dao.EngineRbacPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBetweenPK", minPK, maxPK)
	ret0, _ := ret[0].([]dao.EngineRbacPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBetweenPK indicates an expected call of ListBetweenPK.
func (mr *MockEngineRbacPolicyManagerMockRecorder) ListBetweenPK(minPK, maxPK interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBetweenPK", reflect.TypeOf((*MockEngineRbacPolicyManager)(nil).ListBetweenPK), minPK, maxPK)
}

// ListByPKs mocks base method.
func (m *MockEngineRbacPolicyManager) ListByPKs(pks []int64) ([]dao.EngineRbacPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPKs", pks)
	ret0, _ := ret[0].([]dao.EngineRbacPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPKs indicates an expected call of ListByPKs.
func (mr *MockEngineRbacPolicyManagerMockRecorder) ListByPKs(pks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPKs", reflect.TypeOf((*MockEngineRbacPolicyManager)(nil).ListByPKs), pks)
}

// ListPKBetweenUpdatedAt mocks base method.
func (m *MockEngineRbacPolicyManager) ListPKBetweenUpdatedAt(beginUpdatedAt, endUpdatedAt int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPKBetweenUpdatedAt", beginUpdatedAt, endUpdatedAt)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPKBetweenUpdatedAt indicates an expected call of ListPKBetweenUpdatedAt.
func (mr *MockEngineRbacPolicyManagerMockRecorder) ListPKBetweenUpdatedAt(beginUpdatedAt, endUpdatedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPKBetweenUpdatedAt", reflect.TypeOf((*MockEngineRbacPolicyManager)(nil).ListPKBetweenUpdatedAt), beginUpdatedAt, endUpdatedAt)
}
