// Code generated by MockGen. DO NOT EDIT.
// Source: open_abac_policy.go

// Package mock is a generated GoMock package.
package mock

import (
	dao "iam/pkg/database/dao"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOpenAbacPolicyManager is a mock of OpenAbacPolicyManager interface.
type MockOpenAbacPolicyManager struct {
	ctrl     *gomock.Controller
	recorder *MockOpenAbacPolicyManagerMockRecorder
}

// MockOpenAbacPolicyManagerMockRecorder is the mock recorder for MockOpenAbacPolicyManager.
type MockOpenAbacPolicyManagerMockRecorder struct {
	mock *MockOpenAbacPolicyManager
}

// NewMockOpenAbacPolicyManager creates a new mock instance.
func NewMockOpenAbacPolicyManager(ctrl *gomock.Controller) *MockOpenAbacPolicyManager {
	mock := &MockOpenAbacPolicyManager{ctrl: ctrl}
	mock.recorder = &MockOpenAbacPolicyManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenAbacPolicyManager) EXPECT() *MockOpenAbacPolicyManagerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockOpenAbacPolicyManager) Get(pk int64) (dao.OpenAbacPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", pk)
	ret0, _ := ret[0].(dao.OpenAbacPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOpenAbacPolicyManagerMockRecorder) Get(pk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOpenAbacPolicyManager)(nil).Get), pk)
}

// GetCountByActionBeforeExpiredAt mocks base method.
func (m *MockOpenAbacPolicyManager) GetCountByActionBeforeExpiredAt(actionPK, expiredAt int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCountByActionBeforeExpiredAt", actionPK, expiredAt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCountByActionBeforeExpiredAt indicates an expected call of GetCountByActionBeforeExpiredAt.
func (mr *MockOpenAbacPolicyManagerMockRecorder) GetCountByActionBeforeExpiredAt(actionPK, expiredAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCountByActionBeforeExpiredAt", reflect.TypeOf((*MockOpenAbacPolicyManager)(nil).GetCountByActionBeforeExpiredAt), actionPK, expiredAt)
}

// ListByPKs mocks base method.
func (m *MockOpenAbacPolicyManager) ListByPKs(pks []int64) ([]dao.OpenAbacPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPKs", pks)
	ret0, _ := ret[0].([]dao.OpenAbacPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPKs indicates an expected call of ListByPKs.
func (mr *MockOpenAbacPolicyManagerMockRecorder) ListByPKs(pks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPKs", reflect.TypeOf((*MockOpenAbacPolicyManager)(nil).ListByPKs), pks)
}

// ListPagingByActionPKBeforeExpiredAt mocks base method.
func (m *MockOpenAbacPolicyManager) ListPagingByActionPKBeforeExpiredAt(actionPK, expiredAt, offset, limit int64) ([]dao.OpenAbacPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPagingByActionPKBeforeExpiredAt", actionPK, expiredAt, offset, limit)
	ret0, _ := ret[0].([]dao.OpenAbacPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPagingByActionPKBeforeExpiredAt indicates an expected call of ListPagingByActionPKBeforeExpiredAt.
func (mr *MockOpenAbacPolicyManagerMockRecorder) ListPagingByActionPKBeforeExpiredAt(actionPK, expiredAt, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPagingByActionPKBeforeExpiredAt", reflect.TypeOf((*MockOpenAbacPolicyManager)(nil).ListPagingByActionPKBeforeExpiredAt), actionPK, expiredAt, offset, limit)
}
