// Code generated by MockGen. DO NOT EDIT.
// Source: role.go

// Package mock is a generated GoMock package.
package mock

import (
	pap "iam/pkg/abac/pap"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRoleController is a mock of RoleController interface.
type MockRoleController struct {
	ctrl     *gomock.Controller
	recorder *MockRoleControllerMockRecorder
}

// MockRoleControllerMockRecorder is the mock recorder for MockRoleController.
type MockRoleControllerMockRecorder struct {
	mock *MockRoleController
}

// NewMockRoleController creates a new mock instance.
func NewMockRoleController(ctrl *gomock.Controller) *MockRoleController {
	mock := &MockRoleController{ctrl: ctrl}
	mock.recorder = &MockRoleControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleController) EXPECT() *MockRoleControllerMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockRoleController) BulkCreate(roleType, system string, subjects []pap.Subject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", roleType, system, subjects)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockRoleControllerMockRecorder) BulkCreate(roleType, system, subjects interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockRoleController)(nil).BulkCreate), roleType, system, subjects)
}

// BulkDelete mocks base method.
func (m *MockRoleController) BulkDelete(roleType, system string, subjects []pap.Subject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkDelete", roleType, system, subjects)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkDelete indicates an expected call of BulkDelete.
func (mr *MockRoleControllerMockRecorder) BulkDelete(roleType, system, subjects interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkDelete", reflect.TypeOf((*MockRoleController)(nil).BulkDelete), roleType, system, subjects)
}

// ListSubjectByRole mocks base method.
func (m *MockRoleController) ListSubjectByRole(roleType, system string) ([]pap.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubjectByRole", roleType, system)
	ret0, _ := ret[0].([]pap.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubjectByRole indicates an expected call of ListSubjectByRole.
func (mr *MockRoleControllerMockRecorder) ListSubjectByRole(roleType, system interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubjectByRole", reflect.TypeOf((*MockRoleController)(nil).ListSubjectByRole), roleType, system)
}
