// Code generated by MockGen. DO NOT EDIT.
// Source: policy.go

// Package mock is a generated GoMock package.
package mock

import (
	types "iam/pkg/service/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPolicyEventProducer is a mock of PolicyEventProducer interface.
type MockPolicyEventProducer struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyEventProducerMockRecorder
}

// MockPolicyEventProducerMockRecorder is the mock recorder for MockPolicyEventProducer.
type MockPolicyEventProducerMockRecorder struct {
	mock *MockPolicyEventProducer
}

// NewMockPolicyEventProducer creates a new mock instance.
func NewMockPolicyEventProducer(ctrl *gomock.Controller) *MockPolicyEventProducer {
	mock := &MockPolicyEventProducer{ctrl: ctrl}
	mock.recorder = &MockPolicyEventProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyEventProducer) EXPECT() *MockPolicyEventProducerMockRecorder {
	return m.recorder
}

// PublishABACDeletePolicyEvent mocks base method.
func (m *MockPolicyEventProducer) PublishABACDeletePolicyEvent(deletePolicyIDs []int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishABACDeletePolicyEvent", deletePolicyIDs)
}

// PublishABACDeletePolicyEvent indicates an expected call of PublishABACDeletePolicyEvent.
func (mr *MockPolicyEventProducerMockRecorder) PublishABACDeletePolicyEvent(deletePolicyIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishABACDeletePolicyEvent", reflect.TypeOf((*MockPolicyEventProducer)(nil).PublishABACDeletePolicyEvent), deletePolicyIDs)
}

// PublishRBACDeletePolicyEvent mocks base method.
func (m *MockPolicyEventProducer) PublishRBACDeletePolicyEvent(deletedPolicyPKs []int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishRBACDeletePolicyEvent", deletedPolicyPKs)
}

// PublishRBACDeletePolicyEvent indicates an expected call of PublishRBACDeletePolicyEvent.
func (mr *MockPolicyEventProducerMockRecorder) PublishRBACDeletePolicyEvent(deletedPolicyPKs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRBACDeletePolicyEvent", reflect.TypeOf((*MockPolicyEventProducer)(nil).PublishRBACDeletePolicyEvent), deletedPolicyPKs)
}

// PublishRBACGroupAlterEvent mocks base method.
func (m *MockPolicyEventProducer) PublishRBACGroupAlterEvent(groupPK int64, resourceChangedContents []types.ResourceChangedContent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishRBACGroupAlterEvent", groupPK, resourceChangedContents)
}

// PublishRBACGroupAlterEvent indicates an expected call of PublishRBACGroupAlterEvent.
func (mr *MockPolicyEventProducerMockRecorder) PublishRBACGroupAlterEvent(groupPK, resourceChangedContents interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRBACGroupAlterEvent", reflect.TypeOf((*MockPolicyEventProducer)(nil).PublishRBACGroupAlterEvent), groupPK, resourceChangedContents)
}
