/*
 * TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-权限中心(BlueKing-IAM) available.
 * Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://opensource.org/licenses/MIT
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by MockGen. DO NOT EDIT.
// Source: cache_expression.go

// Package mock is a generated GoMock package.
package mock

import (
	types "iam/pkg/service/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockexpressionCacher is a mock of expressionCacher interface
type MockexpressionCacher struct {
	ctrl     *gomock.Controller
	recorder *MockexpressionCacherMockRecorder
}

// MockexpressionCacherMockRecorder is the mock recorder for MockexpressionCacher
type MockexpressionCacherMockRecorder struct {
	mock *MockexpressionCacher
}

// NewMockexpressionCacher creates a new mock instance
func NewMockexpressionCacher(ctrl *gomock.Controller) *MockexpressionCacher {
	mock := &MockexpressionCacher{ctrl: ctrl}
	mock.recorder = &MockexpressionCacherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockexpressionCacher) EXPECT() *MockexpressionCacherMockRecorder {
	return m.recorder
}

// GetExpressions mocks base method
func (m *MockexpressionCacher) GetExpressions(expressionPKs []int64) ([]types.AuthExpression, []int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpressions", expressionPKs)
	ret0, _ := ret[0].([]types.AuthExpression)
	ret1, _ := ret[1].([]int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetExpressions indicates an expected call of GetExpressions
func (mr *MockexpressionCacherMockRecorder) GetExpressions(expressionPKs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"GetExpressions",
		reflect.TypeOf((*MockexpressionCacher)(nil).GetExpressions),
		expressionPKs,
	)
}

// SetExpressions mocks base method
func (m *MockexpressionCacher) SetExpressions(
	noCacheExpressionPKs []int64,
	noCacheExpressions []types.AuthExpression,
) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetExpressions", noCacheExpressionPKs, noCacheExpressions)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetExpressions indicates an expected call of SetExpressions
func (mr *MockexpressionCacherMockRecorder) SetExpressions(
	noCacheExpressionPKs, noCacheExpressions interface{},
) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"SetExpressions",
		reflect.TypeOf((*MockexpressionCacher)(nil).SetExpressions),
		noCacheExpressionPKs,
		noCacheExpressions,
	)
}
