// Code generated by MockGen. DO NOT EDIT.
// Source: engine.go

// Package mock is a generated GoMock package.
package mock

import (
	prp "iam/pkg/abac/prp"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEnginePolicyManager is a mock of EnginePolicyManager interface.
type MockEnginePolicyManager struct {
	ctrl     *gomock.Controller
	recorder *MockEnginePolicyManagerMockRecorder
}

// MockEnginePolicyManagerMockRecorder is the mock recorder for MockEnginePolicyManager.
type MockEnginePolicyManagerMockRecorder struct {
	mock *MockEnginePolicyManager
}

// NewMockEnginePolicyManager creates a new mock instance.
func NewMockEnginePolicyManager(ctrl *gomock.Controller) *MockEnginePolicyManager {
	mock := &MockEnginePolicyManager{ctrl: ctrl}
	mock.recorder = &MockEnginePolicyManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnginePolicyManager) EXPECT() *MockEnginePolicyManagerMockRecorder {
	return m.recorder
}

// GetMaxPKBeforeUpdatedAt mocks base method.
func (m *MockEnginePolicyManager) GetMaxPKBeforeUpdatedAt(_type string, updatedAt int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxPKBeforeUpdatedAt", _type, updatedAt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaxPKBeforeUpdatedAt indicates an expected call of GetMaxPKBeforeUpdatedAt.
func (mr *MockEnginePolicyManagerMockRecorder) GetMaxPKBeforeUpdatedAt(_type, updatedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxPKBeforeUpdatedAt", reflect.TypeOf((*MockEnginePolicyManager)(nil).GetMaxPKBeforeUpdatedAt), _type, updatedAt)
}

// ListBetweenPK mocks base method.
func (m *MockEnginePolicyManager) ListBetweenPK(_type string, expiredAt, minPK, maxPK int64) ([]prp.EnginePolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBetweenPK", _type, expiredAt, minPK, maxPK)
	ret0, _ := ret[0].([]prp.EnginePolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBetweenPK indicates an expected call of ListBetweenPK.
func (mr *MockEnginePolicyManagerMockRecorder) ListBetweenPK(_type, expiredAt, minPK, maxPK interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBetweenPK", reflect.TypeOf((*MockEnginePolicyManager)(nil).ListBetweenPK), _type, expiredAt, minPK, maxPK)
}

// ListByPKs mocks base method.
func (m *MockEnginePolicyManager) ListByPKs(_type string, pks []int64) ([]prp.EnginePolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPKs", _type, pks)
	ret0, _ := ret[0].([]prp.EnginePolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPKs indicates an expected call of ListByPKs.
func (mr *MockEnginePolicyManagerMockRecorder) ListByPKs(_type, pks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPKs", reflect.TypeOf((*MockEnginePolicyManager)(nil).ListByPKs), _type, pks)
}

// ListPKBetweenUpdatedAt mocks base method.
func (m *MockEnginePolicyManager) ListPKBetweenUpdatedAt(_type string, beginUpdatedAt, endUpdatedAt int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPKBetweenUpdatedAt", _type, beginUpdatedAt, endUpdatedAt)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPKBetweenUpdatedAt indicates an expected call of ListPKBetweenUpdatedAt.
func (mr *MockEnginePolicyManagerMockRecorder) ListPKBetweenUpdatedAt(_type, beginUpdatedAt, endUpdatedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPKBetweenUpdatedAt", reflect.TypeOf((*MockEnginePolicyManager)(nil).ListPKBetweenUpdatedAt), _type, beginUpdatedAt, endUpdatedAt)
}
