// Code generated by MockGen. DO NOT EDIT.
// Source: group_resource_policy.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
)

// MockGroupResourcePolicyService is a mock of GroupResourcePolicyService interface.
type MockGroupResourcePolicyService struct {
	ctrl     *gomock.Controller
	recorder *MockGroupResourcePolicyServiceMockRecorder
}

// MockGroupResourcePolicyServiceMockRecorder is the mock recorder for MockGroupResourcePolicyService.
type MockGroupResourcePolicyServiceMockRecorder struct {
	mock *MockGroupResourcePolicyService
}

// NewMockGroupResourcePolicyService creates a new mock instance.
func NewMockGroupResourcePolicyService(ctrl *gomock.Controller) *MockGroupResourcePolicyService {
	mock := &MockGroupResourcePolicyService{ctrl: ctrl}
	mock.recorder = &MockGroupResourcePolicyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupResourcePolicyService) EXPECT() *MockGroupResourcePolicyServiceMockRecorder {
	return m.recorder
}
